fos_oauth_server:
    db_driver:           orm
    client_class:        ApiUserBundle\Entity\Client
    access_token_class:  ApiUserBundle\Entity\AccessToken
    refresh_token_class: ApiUserBundle\Entity\RefreshToken
    auth_code_class:     ApiUserBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username
        options:
            supported_scopes: user