user_auth_api:
    resource: "@ApiUserBundle/Controller/"
    type:     rest
    prefix:   /api

app:
    resource: "@ApiBundle/Controller/"
    type: rest
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/documentation

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_auth_login:
    path:  /oauth/v2/auth_login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_oauth_server_auth_login_check:
    path:  /oauth/v2/auth_login_check
    defaults: { _controller: FOSUserBundle:Security:check }

#appp:
#    resource: "@ApiBundle/Controller/DefaultController.php"
#    type: annotation
#    prefix: /app

#ApiBundle_oauth_server_security:
#    resource: "@ApiBundle/Resources/config/routing.yml"
#    prefix: /
#    options:
#      i18n: false