<?php

namespace ApiBundle\Repository;

/**
 * BilansanguinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilansanguinRepository extends \Doctrine\ORM\EntityRepository
{
}
