<?php

namespace ApiBundle\Repository;

/**
 * ExamenimagerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamenimagerieRepository extends \Doctrine\ORM\EntityRepository
{
}
