<?php

namespace ApiBundle\Repository;

/**
 * RvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RvRepository extends \Doctrine\ORM\EntityRepository
{
}
