<?php

namespace ApiBundle\Repository;

/**
 * SoininfirmierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoininfirmierRepository extends \Doctrine\ORM\EntityRepository
{
}
